### ISSUE TITLE
Feature Request: Add option to prevent popup closing

### ISSUE THREAD

**Issue by nicekiwi** [authsignal/authsignal-browser#52]
It would be nice if there was a way to prevent the Popup from closing when clicking outside of it, so the only way to close is via the [X] icon. 

Ideally as an option in `PopupHandlerOptions`.

**Comment by hwhmeikle** [comment]
Hi, thanks for the suggestion - I'll take a look into adding this.

**Comment by hwhmeikle** [comment]
We've added an `isClosable` flag to `popupOptions`. Check out https://github.com/authsignal/authsignal-browser/pull/55.

Available in `0.4.1`

Thanks for the suggestion!
